apiVersion: v1
kind: Service
metadata:
  name: aset-nginx
  namespace: aset-nginx
  labels:
    app: aset-nginx
spec:
  type: ClusterIP
  selector:
    app: aset-nginx
  ports:
    - port: 80
      targetPort: 80
