apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpha-nginx
  namespace: aoa-alpha-nginx
  labels:
    app: alpha-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: alpha-nginx
  template:
    metadata:
      labels:
        app: alpha-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
