apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applicationset-demo
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - appName: aset-nginx
            namespace: aset-nginx
            path: argocd-reference-architectures/applicationset-demo/k8s/aset-nginx
          - appName: aset-httpd
            namespace: aset-httpd
            path: argocd-reference-architectures/applicationset-demo/k8s/aset-httpd
          - appName: aset-whoami
            namespace: aset-whoami
            path: argocd-reference-architectures/applicationset-demo/k8s/aset-whoami
  template:
    metadata:
      name: '{{appName}}'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/Github-Arun-Repo/practice-labs.git
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          selfHeal: true
