apiVersion: v1
kind: Pod
spec:
  securityContext:
    runAsUser: 0
    runAsGroup: 0
    fsGroup: 0
  containers:
    - name: maven
      image: maven:3.9.9-eclipse-temurin-21
      command:
        - cat
      tty: true
      volumeMounts:
        - name: workspace-volume
          mountPath: /home/jenkins/agent
        - name: maven-cache
          mountPath: /root/.m2
        - name: owasp-cache
          mountPath: /var/jenkins-cache/owasp-dependency-check
    - name: docker
      image: docker:27-cli
      command:
        - cat
      tty: true
      env:
        - name: DOCKER_HOST
          value: unix:///var/run/docker.sock
      volumeMounts:
        - name: workspace-volume
          mountPath: /home/jenkins/agent
        - name: docker-sock
          mountPath: /var/run/docker.sock
  volumes:
    - name: docker-sock
      hostPath:
        path: /var/run/docker.sock
    - name: workspace-volume
      emptyDir: {}
    - name: maven-cache
      hostPath:
        path: /var/jenkins-cache/m2
        type: DirectoryOrCreate
    - name: owasp-cache
      hostPath:
        path: /var/jenkins-cache/owasp-dependency-check
        type: DirectoryOrCreate